site_name: PHP-HTTP Documentation
site_favicon: favicon.ico
copyright: © 2015 PHP HTTP Team
theme: readthedocs
extra_css:
    - css/extra.css
markdown_extensions:
    - toc:
          permalink: true
    - sane_lists
    - admonition

pages:
    - Home: index.md
    - HTTPlug:
        - httplug/index.md
        - httplug/migrating.md
        - httplug/tutorial.md
        - httplug/virtual-package.md
    - Components:
        - 'Clients & Adapters':
            - Introduction: clients/index.md
            - clients/curl-client.md
            - clients/mock-client.md
            - clients/socket-client.md
            - clients/guzzle5-adapter.md
            - clients/guzzle6-adapter.md
            - clients/react-adapter.md
        - Plugins:
            - plugins/index.md
            - plugins/authentication.md
            - plugins/cache.md
            - plugins/content-length.md
            - plugins/cookie.md
            - plugins/decoder.md
            - plugins/error.md
            - plugins/history.md
            - plugins/journal.md
            - plugins/logger.md
            - plugins/redirect.md
            - plugins/retry.md
            - plugins/stopwatch.md
            - plugins/third-party-plugins.md
        - components/message.md
        - Other Components:
            - components/client-common.md
            - components/discovery.md
            - components/message-factory.md
            - components/promise.md
    - Development:
        - development/code-of-conduct.md
        - development/contributing.md
        - development/license.md
